# Labels:
# Obtener todos los labels
GET http://localhost:8080/api/v1/labels/

### Crear nuevo label
POST http://localhost:8080/api/v1/labels/
Accept: application/json
Content-Type: application/json

{
  "labelName": "NUEVO LABEL",
  "labelColor": "#FF0000"
}


### Editar label mandando id de label(ejemplo con id=1)
PUT http://localhost:8080/api/v1/labels/1
Accept: application/json
Content-Type: application/json

{
    "labelName" : "LabelEditado",
  "labelColor": "#000000"
}

### Eliminar label por id(ejemplo=1)
DELETE http://localhost:8080/api/v1/labels/10



