# Se hicieron todas las verificaciones de la API con postman porque no puedo correr
# Los http(Creo que se puede en IntellijIDEA ULTIMATE que me daran en github student pack)

# Users:
# LOGIN API
# Iniciar sesion
POST http://localhost:8080/api/v1/login
Accept: application/json
Content-Type: application/json

{
    "user": "usuario1",
    "password_hash": "password123"
}

### User API
### Crear nuevo usuario
POST http://localhost:8080/api/v1/users/
Accept: application/json
Content-Type: application/json

{
    "user" : "usuario1",
    "password_hash" : "password123"
}

### Editar contraseña mandando id de usuario(ejemplo con id=2)
PUT http://localhost:8080/api/v1/users/2
Accept: application/json
Content-Type: application/json

{
    "password_hash" : "newpass"
}

