# Tasks:
# Obtener todos los tasks
GET http://localhost:8080/api/v1/tasks/

### Crear nueva task
POST http://localhost:8080/api/v1/tasks/
Accept: application/json
Content-Type: application/json

{
  "taskName": "Tarea de ejemplo",
  "dueDate": "2023-10-31T18:00:00",
  "status": false,
  "completionTime": "2023-10-31T18:00:00",
  "labelId": 1
}



### Editar label tarea id de task(ejemplo con id=1)
PUT http://localhost:8080/api/v1/tasks/16
Accept: application/json
Content-Type: application/json

{
  "taskName": "Tarea COMPLETADA Y EDITADA",
  "dueDate": "2023-10-15T00:00:00Z",
  "status": true,
  "completionTime": "2023-10-15T12:00:00Z",
    "labelId": 3
}


### Eliminar tarea por id(ejemplo=1)
DELETE http://localhost:8080/api/v1/tasks/15



