# Tasks:
# Obtener todos los task-labels
GET http://localhost:8080/api/v1/task-labels/

# Crear nueva task-labels
POST http://localhost:8080/api/v1/task-labels/
Accept: application/json
Content-Type: application/json

{
  "task": 1,      // Reemplaza con el ID de la tarea existente
  "label": 2      // Reemplaza con el ID de la etiqueta existente
}

# Eliminar label por id(ejemplo=1)
DELETE http://localhost:8080/api/v1/tasks-labels/1


